### ISSUE TITLE
Testing whether the code is calling an appropriate SQL statement

### ISSUE THREAD

**Issue by kdmadej** [jimbojsb/pseudo#17]
Should an empty `$expectedResults` array be treated as one with non-parameterized results?

A simple use-case, where the only thing I'm concerned about is whether the code runs the correct query:

``` php
$pdo = new \Pseudo\Pdo();
$pdo->mock('SELECT id FROM table WHERE id = :id');
$query = $pdo->prepare('SELECT id FROM table WHERE id = :id');
$query->execute([':id' => $someId]);
$this->assertTrue(!empty($query->fetchAll(\PDO::FETCH_ASSOC)));
```

results in an error:
`Pseudo\Exception: Cannot get rows with parameters on a non-parameterized result`

The reason being that `execute` passes `$input_parameters` to `getRows`, and the default `Result` (created when no `$expectedResults` are passed) does not have its `isParameterized` attribute set to true. Thus the condition at https://github.com/jimbojsb/pseudo/blob/master/src/Pseudo/Result.php#L49 does not pass and an exception is thrown.

**Comment by cagataygurturk** [comment]
I am experiencing the same issue.
