### ISSUE TITLE
Declaration of Pseudo\Pdo::prepare() should be compatible with PDO::prepare($statement, $options = NULL)

### ISSUE THREAD

**Issue by rkrx** [jimbojsb/pseudo#4]
https://travis-ci.org/rkrx/php-mysql-query-builder/jobs/60594547

**Comment by sman591** [comment]
Was there a solution to this? I'm having the same issue

**Comment by jimbojsb** [comment]
As far as I can tell, ```Pseudo\Pdo::prepare()``` matches the method signature shown in the documentation: http://php.net/manual/en/pdo.prepare.php

**Comment by sman591** [comment]
It looks like it, however I looked a bit deeper into the issue.

In `src/Pseudo/Pdo.php`, the `prepare()` function is defined as so:
```php
public function prepare($statement, array $driver_options = [])
```

However, I changed it to the following, which dismissed the error:
```php
public function prepare($statement, $driver_options = array())
```

Other errors showed up after this, all requiring similar changes to their function definitions. The `array` keyword is common amongst all the errors.

In `PdoStatement.php`:
```php
public function execute(array $input_parameters = null)
// ...
public function fetchObject($class_name = "stdClass", array $ctor_args = null)
```

**Comment by jimbojsb** [comment]
Interesting. Mind sharing what code you're using this with that is triggering these errors? I'd probably be fine with dropping the hints on the methods if we replace it with a type check inside the methods and throw an ```InvalidArgumentException```

**Comment by sman591** [comment]
Sounds like a valid fix. This is the test class that I'm running, nothing more than the example from the readme:

```php
require_once "vendor/autoload.php";
class Test extends PHPUnit_Framework_TestCase
{
    public function testOne() {
        $p = new \Pseudo\Pdo();
        $results = [['id' => 1, 'foo' => 'bar']];
        $p->mock("SELECT id FROM objects WHERE foo='bar'", $results);

        // now use this $p object like you would any regular PDO
        $results = $p->query("SELECT id FROM objects WHERE foo='bar'");
        while ($result = $results->fetch(\PDO::FETCH_ASSOC)) {
            echo $result["foo"];  // bar
        }
    }
}
```
Unfortunately I'm unable to share the entire repo as it is private.

Replacing the function definitions did fix the errors, and the code runs. However, it seems like the while loop tries to run again and I get a `Undefined offset: 1` error.

**Comment by sman591** [comment]
This may be partially related:

https://github.com/jimbojsb/pseudo/commit/78184c5fbe9e82b952503dea0e720f0ca05df3eb#diff-76e71e6567cc984293ceb3fb5d9c4322L28

**Comment by jimbojsb** [comment]
Actually I now think I see the issue. What error reporting are you running? This was built to run in the environments I use which are ```E_ALL & ~(E_NOTICE | E_DEPRECATED | E_STRICT)```, which is why the unit tests don't complain this issue already (I have phpunit.xml set to this as well).

**Comment by sman591** [comment]
Yep, adding that to phpunit.xml fixed all the issues

**Comment by jimbojsb** [comment]
I'd happily accept a pull request to make it 100% strict mode compliant but I won't have time to get to that myself in the near future.

**Comment by jimbojsb** [comment]
Closing this issue and updating the readme to specifically call out the error reporting mode
