### ISSUE TITLE
missing support for FETCH_CLASS

### ISSUE THREAD

**Issue by bar-yariv** [jimbojsb/pseudo#9]
Pseudo did great job except for when i tried testing FETCH_CLASS. I noticed that there is no support for it in the code. any chance for some help with it?

**Comment by jimbojsb** [comment]
This is not trivial to implement, it's why I initially skipped it. I'll take another look.

**Comment by al-sade** [comment]
great thank you

**Comment by giladaya** [comment]
That would definitely be a great upgrade to this useful library.
Thanks

**Comment by jimbojsb** [comment]
Is anyone using ```PDO::FETCH_PROPS_LATE``` ? I'm not sure it's even possible to support this in userland PHP code.

**Comment by giladaya** [comment]
I'm only using plain PDO::FETCH_CLASS.

Why do you think it won't be possible to support this in userland PHP code?
Using PDO::FETCH_PROPS_LATE would seem simpler to implement (instanciate the class normally, then assign values from the mock data)
Using PDO::FETCH_CLASS might be more complicated as you need to instantiate an object without invoking the constructor -> assign values -> call the constructor. I think this can be done with reflection methods, but haven't tried (EG using ReflectionClass::newInstanceWithoutConstructor)
